Update s3-deploy.yaml

diff --git a/.github/workflows/s3-deploy.yaml b/.github/workflows/s3-deploy.yaml
--- a/.github/workflows/s3-deploy.yaml
+++ b/.github/workflows/s3-deploy.yaml
@@ -5,20 +5,39 @@ on:
     workflows:
       - main
     branches:
-      - gh-pages
-        
+      - main
+    types: 
+      - completed
+     
 jobs:
   deploy:
     name: Build And Upload to S3
     runs-on: ubuntu-latest
 
     steps:
-      - name: Configure AWS credentials from account
-        uses: aws-actions/configure-aws-credentials@v1
+      - uses: webfactory/ssh-agent@v0.5.0
         with:
-            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
-            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-            aws-region: ap-northeast-1
+          ssh-private-key: ${{ secrets.GH_PAGES_DEPLOY }}
+          
+      - uses: aws-actions/configure-aws-credentials@v1
+      - name: Configure AWS credentials from account
+        if: ${{ github.event.workflow_run.conclusion != 'success' }}
+        run: |
+          echo '::error::Previous workflow was failed'
+          exit 1
+
+          with:
+              aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
+              aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+              aws-region: ap-northeast-1
 
       - name: Copy Files to s3
-        run: aws s3 sync . s3://pca-knowledge-base-bucket --exact-timestamps --delete # 同じファイルサイズでも同期されるように
+        env:
+          USE_SSH: true
+          GIT_USER: git
+        run: |
+          git config --global user.email "actions@github.com"
+          git config --global user.name "gh-actions"
+          git branch -M gh-pages
+
+          aws s3 sync . s3://pca-knowledge-base-bucket --exact-timestamps --delete # 同じファイルサイズでも同期されるように
